@host = http://localhost:5115
@user = /api/user
@auth = /api/auth

###

GET {{host}}/health-check

###

GET {{host}}{{user}}

###

GET {{host}}{{user}}/c3cea2f4-b3ad-4a87-83c8-8c181ef210ce

###
POST {{host}}{{user}}/
Content-Type: application/json

{
  "firstName": "FirstName",
  "lastName": "LastName",
  "age": 30,
  "phoneNumber": "+60123456789",
  "occupation": "Student",
  "ethnicity": "Asian",
  "emailAddress": "example1@gmail.com",
  "password": "123123123"
}

###

DELETE {{host}}{{user}}/c3cea2f4-b3ad-4a87-83c8-8c181ef210ce

###

PUT {{host}}{{user}}/c3cea2f4-b3ad-4a87-83c8-8c181ef210ce
Content-Type: application/json

{
  "lastName": "Guy"
}

###

POST {{host}}{{auth}}/login
Content-Type: application/json

{
  "emailAddress": "en@gmail.com",
  "password": "asdasdasd",
}

###

POST {{host}}{{auth}}/register
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "User",
  "age": 19,
  "phoneNumber": "+60123456789",
  "occupation": "Backend Developer",
  "ethnicity": "Indian",
  "emailAddress": "en@gmail.com",
  "password": "asdasdasd"
}