@host = http://localhost:5115
@user = /api/user
@auth = /api/auth

###

GET {{host}}/health

###

GET {{host}}{{user}}

###

GET {{host}}{{user}}/aa76393b-b481-418d-8a1e-117377d8836d

###
POST {{host}}{{user}}/
Content-Type: application/json

{
  "firstName": "FirstName",
  "lastName": "LastName",
  "age": 30,
  "phoneNumber": "+60123456789",
  "occupation": "Student",
  "ethnicity": "Asian",
  "emailAddress": "example2@gmail.com",
  "password": "123123123"
}

###

DELETE {{host}}{{user}}/aa76393b-b481-418d-8a1e-117377d8836d

###

PUT {{host}}{{user}}/c0fe3903-81b4-42cb-9f15-79b0159cf82f
Content-Type: application/json

{
  "lastName": "Last"
}

###

POST {{host}}{{auth}}/login
Content-Type: application/json

{
  "emailAddress": "en@gmail.com",
  "password": "asdasdasd"
}

###

POST {{host}}{{auth}}/register
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "User",
  "age": 19,
  "phoneNumber": "+60123456789",
  "occupation": "Backend Developer",
  "ethnicity": "Indian",
  "emailAddress": "en@gmail.com",
  "password": "asdasdasd"
}