### user

GET http://localhost:5115/health HTTP/1.1


### 

GET http://localhost:5115/api/users HTTP/1.1


### 

GET http://localhost:5115/api/users/aa76393b-b481-418d-8a1e-117377d8836d HTTP/1.1


### 

POST http://localhost:5115/api/users/ HTTP/1.1
Content-Type: application/json

{
  "age": 30,
  "email": "example5@gmail.com",
  "ethnicity": "Indian",
  "firstName": "FirstName",
  "lastName": "LastName",
  "occupation": "Student",
  "password": "123AsdQwe",
  "phoneNumber": "+60123456789"
}


### 

DELETE http://localhost:5115/api/users/aa76393b-b481-418d-8a1e-117377d8836d HTTP/1.1


### 

PUT http://localhost:5115/api/users/c0fe3903-81b4-42cb-9f15-79b0159cf82f HTTP/1.1
Content-Type: application/json

{
  "lastName": "Last"
}


### 

POST http://localhost:5115/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "emailAddress": "en@gmail.com",
  "password": "asdasdasd"
}


### 

POST http://localhost:5115/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "en@gmail.com",
  "password": "asdasdasd"
}
